[ 2023-05-03 12:05:21,011 ] 224 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[ 2023-05-03 12:05:21,011 ] 224 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-05-03 12:05:35,845 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 12:05:35] "GET / HTTP/1.1" 200 -
[ 2023-05-03 12:05:39,871 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 12:05:39] "GET /predictdata HTTP/1.1" 200 -
[ 2023-05-03 12:05:52,291 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/utils.py", line 58, in load_object
    with open(file_path, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/pipeline/predict_pipeline.py", line 17, in predict
    preprocessor=load_object(file_path=preprocessor_path)
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/utils.py", line 62, in load_object
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/utils.py] line number [58] error message[[Errno 2] No such file or directory: 'artifacts/preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/app.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/pipeline/predict_pipeline.py", line 24, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/pipeline/predict_pipeline.py] line number [17] error message[Error occured in python script name [/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/src/utils.py] line number [58] error message[[Errno 2] No such file or directory: 'artifacts/preprocessor.pkl']]
[ 2023-05-03 12:05:52,293 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 12:05:52] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
